name: fakestore-backend-drf
services:
  app:
    image: eduardosilvasc/fakestore-backend-drf:latest
    environment:
      - MODE=DEVELOPMENT #  possible values are: DEVELOPMENT, PRODUCTION, MIGRATE
      - SECRET_KEY=%vym@cjw-=0%yycqd-9$l7olx&c48%i*!14(gsd7kzm%g4_bt&
      - DEBUG=True #  possible values are: True, False
      - PASSAGE_APP_ID=C5cF3dHXcdD59l1qaPvQ2FiT
      - PASSAGE_API_KEY=VhefIOEp3g.OrFMZwb4yAFaofl4fJ9upgvhIOsVBSx4NCQYZZ0BFMivv1KpZDJg6qefvWxlUW1n
    ports:
      - 8000:8000